# docker-compose.yml
version: "3.8"
services:
  minikube-dind:
    build: .
    privileged: true
    container_name: minikube-dind
    environment:
      - K8S_VERSION=v1.27.3
      - MINIKUBE_VERSION=v1.31.2
    volumes:
      - minikube-data:/var/lib/docker
      - minikube-logs:/var/log/minikube
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
volumes:
  minikube-data:
  minikube-logs:
