name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Minikube Setup and Status Check
    steps:
      - name: start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          minikube-version: 1.24.0
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.22.3
          nodes: 2
          cpus: 4
          memory: 4000m
          cni: bridge
          addons: registry,ingress
          extra-config: 'kubelet.max-pods=10'
          feature-gates: 'DownwardAPIHugePages=true'
          mount-path: '/Users/user1/test-files:/testdata'
          wait: false
          insecure-registry: 'localhost:5000'

      - name: Display Minikube Status
        run: |
          echo "Minikube version is $(minikube version)"
          minikube status
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -A

      - name: Verify Ingress Addon
        run: |
          kubectl get pods -n ingress
